configs = {
    "DeepSlim": {
        "model_name": "DeepSlim",
        "num_blocks": [6, 4, 3],
        "conv_kernel_sizes": [3, 3, 3],
        "shortcut_kernel_sizes": [1, 1, 1],
        "num_channels": 64,
        "avg_pool_kernel_size": 8,
        "drop": 0,
        "squeeze_and_excitation": 1,
        "grad_clip": 0.15,
        "max_epochs": 150,
        "optim": "AdamW",
        "lr_sched": "cosineannealingwarmrestarts",
        "momentum": 0.9,
        "lr": 0.09,
        "weight_decay": 0.001,
        "batch_size": 256,
        "num_workers": 16,
        "data_augmentation": 1,
        "data_normalize": 1,
        "lookahead": 1,
        "label_smoothing": 0.15,
        "use_amp": False,
        "early_stopping_patience": 40,
        "min_delta": 0.0009
    },
    "MyResNet": {
        "model_name": "MyResNet",
        "num_blocks": [5, 4, 3],
        "conv_kernel_sizes": [3, 3, 3],
        "shortcut_kernel_sizes": [1, 1, 1],
        "num_channels": 64,
        "avg_pool_kernel_size": 8,
        "drop": 0,
        "squeeze_and_excitation": 1,
        "grad_clip": 0.15,
        "max_epochs": 200,
        "optim": "sgd",
        "lr_sched": "CosineAnnealingLR",
        "momentum": 0.9,
        "lr": 0.09,
        "weight_decay": 0.0005,
        "batch_size": 256,
        "num_workers": 16,
        "data_augmentation": 1,
        "data_normalize": 1,
        "lookahead": 1,
        "label_smoothing": 0.05,
        "use_amp": False,
        "early_stopping_patience": 40,
        "min_delta": 0.0009
    },
    "PreNet": {
        "model_name": "PreNet",
        "num_blocks": [4, 3, 3],
        "conv_kernel_sizes": [5, 3, 3],
        "shortcut_kernel_sizes": [1, 1, 1],
        "num_channels": 64,
        "avg_pool_kernel_size": 8,
        "drop": 0,
        "squeeze_and_excitation": 1,
        "grad_clip": 0.1,
        "max_epochs": 200,
        "optim": "sgd",
        "lr_sched": "CosineAnnealingLR",
        "momentum": 0.9,
        "lr": 0.1,
        "weight_decay": 0.0005,
        "batch_size": 256,
        "num_workers": 16,
        "data_augmentation": 1,
        "data_normalize": 1,
        "lookahead": 1,
        "label_smoothing": 0.1,
        "use_amp": True
    },
    "ResMix": {
        "model_name": "ResMix",
        "num_blocks": [3, 4, 3],
        "conv_kernel_sizes": [3, 5, 3],
        "shortcut_kernel_sizes": [1, 3, 1],
        "num_channels": 64,
        "avg_pool_kernel_size": 8,
        "drop": 0.1,
        "squeeze_and_excitation": True,
        "grad_clip": 0.08,
        "max_epochs": 150,
        "optim": "sgd",
        "lr_sched": "CosineAnnealingWarmRestarts",
        "momentum": 0.9,
        "lr": 0.05,
        "weight_decay": 0.0008,
        "batch_size": 256,
        "num_workers": 16,
        "data_augmentation": 1,
        "data_normalize": 1,
        "lookahead": 1,
        "label_smoothing": 0.05,
        "use_amp": True,
        "early_stopping_patience": 12,
        "min_delta": 0.0009
    }, 
    "ResNetX": {
        "model_name": "ResNetX",
        "num_blocks": [5, 4, 3],
        "conv_kernel_sizes": [3, 3, 3],
        "shortcut_kernel_sizes": [1, 1, 1],
        "num_channels": 64,
        "avg_pool_kernel_size": 8,
        "drop": 0,
        "squeeze_and_excitation": 1,
        "grad_clip": 0.1,
        "max_epochs": 200,
        "optim": "sgd",
        "lr_sched": "CosineAnnealingLR",
        "momentum": 0.9,
        "lr": 0.1,
        "weight_decay": 0.0005,
        "batch_size": 256,
        "num_workers": 16,
        "data_augmentation": 1,
        "data_normalize": 1,
        "cardinality": 16,
        "lookahead": 1,
        "label_smoothing": 0.1,
        "use_amp": True,
        "early_stopping_patience": 30,
        "min_delta": 0.0001
    },
    "ResReg": {
        "model_name": "ResReg",
        "num_blocks": [3, 3, 2],
        "conv_kernel_sizes": [3, 3, 3],
        "shortcut_kernel_sizes": [1, 1, 1],
        "num_channels": 70,
        "avg_pool_kernel_size": 8,
        "drop": 0,
        "squeeze_and_excitation": 1,
        "grad_clip": 0.1,
        "max_epochs": 200,
        "optim": "sgd",
        "lr_sched": "CosineAnnealingLR",
        "momentum": 0.9,
        "lr": 0.1,
        "weight_decay": 0.0005,
        "batch_size": 128,
        "num_workers": 16,
        "data_augmentation": 1,
        "data_normalize": 1,
        "lookahead": 1,
        "label_smoothing": 0.1,
        "use_amp": True
    },
    "ResWide": {
        "model_name": "ResWide",
        "num_blocks": [3, 2, 1],  # Reduced depth
        "conv_kernel_sizes": [3, 3, 5],  
        "shortcut_kernel_sizes": [1, 1, 1],  
        "num_channels": 90,  # Wider channels
        "avg_pool_kernel_size": 8,
        "drop": 0.1,
        "squeeze_and_excitation": 0,
        "grad_clip": 0.1,
        "max_epochs": 200,
        "optim": "adamw",
        "lr_sched": "OneCycleLR",
        "momentum": 0.85,
        "lr": 0.003,
        "weight_decay": 0.001,
        "batch_size": 256,
        "num_workers": 16,
        "data_augmentation": 1,
        "data_normalize": 1,
        "lookahead": 1,
        "label_smoothing": 0.1,
        "use_amp": True,
        "early_stopping_patience": 12,
        "min_delta": 0.0009
    }
}
